[package]
name    = "inko"
version = "0.0.1"
authors = ["Yorick Peterse <yorickpeterse@gmail.com>"]

[lib]
name    = "libinko"
doctest = false

[[bin]]
name = "ivm"
test = false

[dependencies]
getopts = "^0.2"
num_cpus = "^1.0"
rayon = "^1.0"
parking_lot = { version = "^0.5", features = ["nightly"] }
fnv = "^1.0"
colored = "^1.6"
time = "^0.1"
num-integer = "^0.1"
float-cmp = "^0.4"
num-bigint = "^0.2"
num-traits = "^0.2"

# [dependencies.rug]
# version = "^1.1"
# default-features = false
# features = ["integer"]

[features]
default = ["prefetch"]

# Enables the use of prefetching to improve performance in various areas. This
# requires a nightly build of Rust.
prefetch = []
